### ISSUE TITLE
bug: `viem` failing to import where WebSocket is not available

### ISSUE THREAD

**Issue by FrederikBolding** [wevm/viem#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0

### Current Behavior

`viem` throws on import in CommonJS in environments where WebSockets is not available. 

Since the import for `isows` is not treeshaken out it will throw once it hits: https://github.com/wevm/isows/blob/main/src/utils.ts#L6 even when the user is not attempting to use WebSocket functionality.

### Expected Behavior

I would expect `viem` to handle the lack of WebSocket gracefully and only fail an attempt to use it is made.

### Steps To Reproduce

In the [reproducible example](https://github.com/FrederikBolding/viem-snap-repro) follow the following steps:

```
yarn
cd packages/snap
yarn start
```

Notice the following error in your console:

```
  [Error <Object <[Object: null prototype] {}>>: `WebSocket` is not supported in this environment
    at eval (eval at <anonymous> (eval at makeEvaluate (/home/frederik/dev/viem-snap-repro/node_modules/ses/dist/ses.cjs:6141:27)), <anonymous>:1:480221)
    at 6331 (eval at <anonymous> (eval at makeEvaluate (/home/frederik/dev/viem-snap-repro/node_modules/ses/dist/ses.cjs:6141:27)), <anonymous>:1:480283)
    at r (eval at <anonymous> (eval at makeEvaluate (/home/frederik/dev/viem-snap-repro/node_modules/ses/dist/ses.cjs:6141:27)), <anonymous>:1:480384)
    at 9158 (eval at <anonymous> (eval at makeEvaluate (/home/frederik/dev/viem-snap-repro/node_modules/ses/dist/ses.cjs:6141:27)), <anonymous>:1:458991)
    at r (eval at <anonymous> (eval at makeEvaluate (/home/frederik/dev/viem-snap-repro/node_modules/ses/dist/ses.cjs:6141:27)), <anonymous>:1:480384)
    at 8624 (eval at <anonymous> (eval at makeEvaluate (/home/frederik/dev/viem-snap-repro/node_modules/ses/dist/ses.cjs:6141:27)), <anonymous>:1:260624)
    at r (eval at <anonymous> (eval at makeEvaluate (/home/frederik/dev/viem-snap-repro/node_modules/ses/dist/ses.cjs:6141:27)), <anonymous>:1:480384)
    at eval (eval at <anonymous> (eval at makeEvaluate (/home/frederik/dev/viem-snap-repro/node_modules/ses/dist/ses.cjs:6141:27)), <anonymous>:1:480892)]
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/FrederikBolding/viem-snap-repro

**Comment by jxom** [comment]
Fixed in 2.0.3.
