### ISSUE TITLE
bug: Blob Transactions Guide code isn't functional

### ISSUE THREAD

**Issue by remarcable** [wevm/viem#1980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.8.13

### Current Behavior

After moving the files from https://viem.sh/docs/guides/blob-transactions into a fresh project, the project fails with the following error message:

```
Error: Could not locate the bindings file. Tried:
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/build/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/build/Debug/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/build/Release/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/out/Debug/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/Debug/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/out/Release/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/Release/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/build/default/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/compiled/18.18.0/linux/x64/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/addon-build/release/install-root/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/addon-build/debug/install-root/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/addon-build/default/install-root/kzg.node
 → /home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/lib/binding/node-v108-linux-x64/kzg.node
    at bindings (/home/projects/stackblitz-starters-q8etxu/node_modules/bindings/bindings.js:126:9)
    at Object.eval (/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/lib/kzg.js:7:37)
    at Object.function (https://stackblitzstartersq8etxu-jmzt.w-credentialless-staticblitz.com/blitz.810981ba.js:352:194507)
    at Module._compile (node:internal/modules/cjs/loader:54:14871)
    at Module._extensions..js (node:internal/modules/cjs/loader:54:15550)
    at Module.load (node:internal/modules/cjs/loader:54:13457)
    at Module._load (node:internal/modules/cjs/loader:54:10535)
    at _0x4300f1.executionFunctionOrLineOffset (node:internal/modules/esm/translators:189:2451)
    at _0x4300f1._evaluate (https://stackblitzstartersq8etxu-jmzt.w-credentialless-staticblitz.com/blitz.810981ba.js:352:378111)
    at _0x4300f1._evaluate (https://stackblitzstartersq8etxu-jmzt.w-credentialless-staticblitz.com/blitz.810981ba.js:352:378240) {
  tries: [
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/build/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/build/Debug/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/build/Release/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/out/Debug/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/Debug/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/out/Release/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/Release/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/build/default/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/compiled/18.18.0/linux/x64/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/addon-build/release/install-root/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/addon-build/debug/install-root/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/addon-build/default/install-root/kzg.node',
    '/home/projects/stackblitz-starters-q8etxu/node_modules/c-kzg/lib/binding/node-v108-linux-x64/kzg.node'
  ]
}
```

https://stackblitz.com/edit/stackblitz-starters-picxmh?file=kzg.mjs

### Expected Behavior

I expect this to submit a blob to the network.

### Steps To Reproduce

Please have a look at the minimal reproduction and after installing node modules, run `node index.mjs`. The private key is a random stub.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/stackblitz-starters-picxmh?file=index.mjs&view=editor

### Anything else?

Thanks for your awesome work!

**Comment by tunnckoCore** [comment]
@remarcable just use `kzg-wasm`, it's pretty stable no need for setup or anything, it has it's own trusted setup which is loaded by default, or you can pass own.

```js
import { loadKZG } from 'kzg-wasm';

const kzg = await loadKZG(/* optional trustedSetup object here */);

const tx = wallet.sendTransaction({
  kzg
})
```

**Comment by jxom** [comment]
This is unrelated to Viem. Your package manager should run postinstall scripts to set up node-gyp bindings. Might be worth creating an issue in c-kzg or node-gyp.
