### ISSUE TITLE
bug: failed to fetch balance

### ISSUE THREAD

**Issue by facilficom** [wevm/viem#2123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version
    "@tanstack/react-query": "^5.29.0",
    "@web3modal/siwe": "^4.1.5",
    "@web3modal/wagmi": "^4.1.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-refresh": "^0.14.0",
    "react-router-dom": "^6.17.0",
    "react-scripts": "^5.0.1",
    "viem": "^2.9.16",
    "wagmi": "^2.5.19"
node 20+

### Current Behavior

Details: Failed to fetch
Version: viem@2.9.16
    at Object.request (http://localhost:3000/static/js/bundle.js:133136:15)
    at async fn (http://localhost:3000/static/js/bundle.js:123995:60)
    at async request (http://localhost:3000/static/js/bundle.js:124001:14)
    at async delay.count.count (http://localhost:3000/static/js/bundle.js:129857:16)
    at async attemptRetry (http://localhost:3000/static/js/bundle.js:132984:22)

### Steps To Reproduce
URL: https://rpc.walletconnect.com/v1/?chainId=eip155:97&projectId=(projectid)
Request body: {"method":"eth_getBalance","params":["(wallet)","latest"]}

// balance.js
import React, { useState, useEffect } from 'react';
import { useBalance, useChainId } from 'wagmi';

function BalanceComponent({ account, symbolfortext }) {

    const [balance, setbalance] = useState(0);
    const chainId = useChainId()
    const { data: balanceBNB } = useBalance({
        address: account,
        blockTag: 'latest',
    })

    useEffect(() => {
        if (Number(balanceBNB?.value) >= 0) {
            const bal = Number(balanceBNB?.value) / 10 ** 18;
            const balanceok = (parseFloat(bal).toFixed(9));
            setbalance(balanceok);
        }
    }, [balanceBNB, account, chainId]);

    return (
        <p id="balancerifa"> Balance: <span id="secondary">{balance} {symbolfortext}</span></p>
    );
}

export default BalanceComponent;

### Anything else?
I've never had this problem before. with the same file.
why this problem? on local host give me this every 3 seconds, its so annoying. thanks you so much!

**Comment by facilficom** [comment]
i have node 20+

**Comment by facilficom** [comment]
apparently it's a problem if I have watchcontractevent active in the code
