### ISSUE TITLE
Client doesn't work correctly with anvil

### ISSUE THREAD

**Issue by poolpitako** [wevm/viem#2450]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.16.4

### Current Behavior

Calling `client.getBlockNumber()` or `client.getChainId()` doesn't work correctly with anvil.

### Expected Behavior

viem should work correctly with anvil.

### Steps To Reproduce

Start an anvil fork

```bash
anvil --chain-id 100 --fork-url "http://my_node_ip:my_node_port" --host "0.0.0.0" --block-time 30
```

Run the following code:

```ts
import { createPublicClient, http } from 'viem'
import { gnosis } from 'viem/chains'

const client = createPublicClient({
  chain: gnosis,
  transport: http("http://localhost:8545"),
  //transport: http("http://my_node_ip:my_node_port"),
})

const main = async () => {
    console.log("block #", await client.getBlockNumber())
    console.log("chain id", await client.getChainId())
}

main()
```

You will notice that using a random node it works but it fails when using anvil.

### Anything else?

Working

```bash
$ curl --header "Content-Type: application/json" -X POST --data '{"method":"eth_chainId","id":1,"jsonrpc":"2.0"}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x64"}%
```

Not working
```bash
$ curl --header "Content-Type: application/json" -X POST --data '{"method":"eth_chainId"}' http://localhost:8545
{"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid request"}}%

**Comment by poolpitako** [comment]
@jxom Ticket contains information on how to reproduce.
Repro steps require an anvil instance and I can't do that online.

**Comment by jxom** [comment]
The second snippet you provided is an invalid JSON-RPC request (ie. missing `id`, `jsonrpc` fields). Unsure why your first snippet is breaking. I cannot reproduce. Please follow the [instructions here](https://github.com/wevm/viem/issues/2450#issuecomment-2198087497) and I will be more than happy to look into it.

**Comment by poolpitako** [comment]
@jxom are you testing against an anvil node?
i can try setup a repo with a docker compose running anvil + a viem script but it should be reproducible if you run the sample code against a local anvil fork.

**Comment by jxom** [comment]
yes. the [entire viem test suite](https://github.com/wevm/viem/actions/runs/9718101982/job/26825206733) is ran against a local anvil node.

please post a minimal reproduction with minimal dependencies (not even docker).

**Comment by poolpitako** [comment]
@jxom perfect. I found my issue.

I was running on a terminal with an old node version. 

```
$npx -v
7.10.0

$ npx ts-node src/index.ts
/Users/user/dev/chainId/node_modules/viem/utils/rpc/http.ts:141
        throw new HttpRequestError({
              ^
HttpRequestError: HTTP request failed.

URL: http://127.0.0.1:8545
Request body: {"method":"eth_blockNumber"}

Details: Request is not defined
Version: viem@2.16.4
    at Object.request (/Users/user/dev/chainId/node_modules/viem/utils/rpc/http.ts:141:15)
    at async fn (/Users/user/dev/chainId/node_modules/viem/clients/transports/http.ts:125:19)
    at async request (/Users/user/dev/chainId/node_modules/viem/clients/transports/http.ts:130:39)
    at async delay.count.count (/Users/user/dev/chainId/node_modules/viem/utils/buildRequest.ts:118:22)
    at async attemptRetry (/Users/user/dev/chainId/node_modules/viem/utils/promise/withRetry.ts:44:22) {
  details: 'Request is not defined',
  docsPath: undefined,
  metaMessages: [
    'URL: http://127.0.0.1:8545',
    'Request body: {"method":"eth_blockNumber"}'
  ],
  shortMessage: 'HTTP request failed.',
  version: 'viem@2.16.4',
  cause: ReferenceError: Request is not defined
      at response.errorInstance.request_js_1.TimeoutError.body.body (/Users/user/dev/chainId/node_modules/viem/utils/rpc/http.ts:103:29)
      at /Users/user/dev/chainId/node_modules/viem/utils/promise/withTimeout.ts:36:23
      at /Users/user/dev/chainId/node_modules/viem/utils/promise/withTimeout.ts:43:7
      at new Promise (<anonymous>)
      at withTimeout (/Users/user/dev/chainId/node_modules/viem/utils/promise/withTimeout.ts:22:10)
      at Object.request (/Users/user/dev/chainId/node_modules/viem/utils/rpc/http.ts:79:43)
      at fn (/Users/user/dev/chainId/node_modules/viem/clients/transports/http.ts:125:35)
      at request (/Users/user/dev/chainId/node_modules/viem/clients/transports/http.ts:130:45)
      at delay.count.count (/Users/user/dev/chainId/node_modules/viem/utils/buildRequest.ts:118:28)
      at attemptRetry (/Users/user/dev/chainId/node_modules/viem/utils/promise/withRetry.ts:44:28),
  body: { method: 'eth_blockNumber', params: undefined },
  headers: undefined,
  status: undefined,
  url: 'http://127.0.0.1:8545'
}
```

When I saw the `Request body: {"method":"eth_blockNumber"}` I assumed `id` and `jsonrpc` was not passed instead of the, now obvious, `Request is not defined`.

Sorry for the time wasted.
